type: "transformation"
version: "1.0"
pipeline:
  components:
    Silver (customers_clean):
      type: "table-input"
      parameters:
        componentName: "Silver (customers_clean)"
        database: "SCD_TYPE_2"
        schema: "silver"
        targetTable: "customers_clean"
        columnNames:
        - "c_id"
        - "name"
        - "email"
        - "city"
        - "updated_at"
        timeOffset:
    Detect Changes:
      type: "detect-changes"
      sources:
      - "Silver (customers_clean)"
      - "SQL (gold_current)"
      parameters:
        componentName: "Detect Changes"
        masterTable: "SQL (gold_current)"
        matchKeys:
        - "c_id"
        compareColumns:
        - "email"
        - "city"
        outputColumnMapping:
        - - "compare_name"
          - "name"
        - - "compare_email"
          - "email"
        - - "compare_city"
          - "city"
        - - "compare_updated_at"
          - "updated_at"
        indicatorColumn: "Indicator"
    Gold (dim_customers):
      type: "table-input"
      parameters:
        componentName: "Gold (dim_customers)"
        database: "SCD_TYPE_2"
        schema: "gold"
        targetTable: "dim_customers"
        columnNames:
        - "c_id"
        - "name"
        - "email"
        - "city"
        - "updated_at"
        timeOffset:
    Gold Update (dim_customers):
      type: "table-update"
      sources:
      - "C (Change Indicator)"
      parameters:
        componentName: "Gold Update (dim_customers)"
        warehouse: "[Environment Default]"
        database: "SCD_TYPE_2"
        schema: "gold"
        targetTable: "dim_customers"
        targetAlias: "target"
        sourceAlias: "input"
        joinExpression:
        - - "\"target\".\"c_id\" = \"input\".\"c_id\""
          - "Case"
        whenMatched:
        - - "\"input\".\"Indicator\" = 'C'"
          - "Update"
        updateMapping:
        - - "name"
          - "name"
        - - "email"
          - "email"
        - - "city"
          - "city"
        - - "updated_at"
          - "updated_at"
        includeNotMatched: "No"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    N (New Indicator):
      type: "filter"
      sources:
      - "Detect Changes"
      parameters:
        componentName: "N (New Indicator)"
        mode: "Basic"
        filterConditions:
        - - "Indicator"
          - "Is"
          - "Equal to"
          - "N"
        combineCondition: "And"
    C (Change Indicator):
      type: "filter"
      sources:
      - "Detect Changes"
      parameters:
        componentName: "C (Change Indicator)"
        mode: "Basic"
        filterConditions:
        - - "Indicator"
          - "Is"
          - "Equal to"
          - "C"
        combineCondition: "And"
    Gold New (dim_customers):
      type: "table-update"
      sources:
      - "N (New Indicator)"
      parameters:
        componentName: "Gold New (dim_customers)"
        warehouse: "[Environment Default]"
        database: "SCD_TYPE_2"
        schema: "gold"
        targetTable: "dim_customers"
        targetAlias: "target"
        sourceAlias: "input"
        joinExpression:
        - - "\"target\".\"c_id\" = \"input\".\"c_id\""
          - "Case"
        whenMatched:
        updateMapping:
        - - "name"
          - "name"
        - - "email"
          - "email"
        - - "city"
          - "city"
        - - "updated_at"
          - "updated_at"
        includeNotMatched: "Yes"
        insertMapping:
        - - "c_id"
          - "c_id"
        - - "name"
          - "name"
        - - "email"
          - "email"
        - - "city"
          - "city"
        - - "updated_at"
          - "updated_at"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    D (Delete Indicator):
      type: "filter"
      sources:
      - "Detect Changes"
      parameters:
        componentName: "D (Delete Indicator)"
        mode: "Basic"
        filterConditions:
        - - "Indicator"
          - "Is"
          - "Equal to"
          - "D"
        combineCondition: "And"
    Gold Delete (dim_customers):
      type: "table-update"
      sources:
      - "D (Delete Indicator)"
      parameters:
        componentName: "Gold Delete (dim_customers)"
        warehouse: "[Environment Default]"
        database: "SCD_TYPE_2"
        schema: "gold"
        targetTable: "dim_customers"
        targetAlias: "target"
        sourceAlias: "input"
        joinExpression:
        - - "\"target\".\"c_id\" = \"input\".\"c_id\""
          - "Case"
        whenMatched:
        updateMapping:
        - - "name"
          - "name"
        - - "email"
          - "email"
        - - "city"
          - "city"
        - - "updated_at"
          - "updated_at"
        includeNotMatched: "Yes"
        insertMapping:
        - - "c_id"
          - "c_id"
        - - "name"
          - "name"
        - - "email"
          - "email"
        - - "city"
          - "city"
        - - "updated_at"
          - "updated_at"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    SQL (gold_current):
      type: "sql"
      parameters:
        componentName: "SQL (gold_current)"
        query: "SELECT\r\n    \"c_id\",\r\n    \"name\",\r\n    \"email\",\r\n   \
          \ \"city\"\r\nFROM \"SCD_TYPE_2\".\"gold\".\"dim_customers\"\r\nWHERE \"\
          is_current\" = TRUE"
design:
  components:
    Silver (customers_clean):
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    Detect Changes:
      position:
        x: 210
        "y": 60
      tempMetlId: 2
    Gold (dim_customers):
      position:
        x: 0
        "y": 350
      tempMetlId: 3
    Gold Update (dim_customers):
      position:
        x: 780
        "y": 180
      tempMetlId: 4
    N (New Indicator):
      position:
        x: 450
        "y": 60
      tempMetlId: 6
    C (Change Indicator):
      position:
        x: 450
        "y": 180
      tempMetlId: 7
    Gold New (dim_customers):
      position:
        x: 780
        "y": 60
      tempMetlId: 9
    D (Delete Indicator):
      position:
        x: 450
        "y": -70
      tempMetlId: 10
    Gold Delete (dim_customers):
      position:
        x: 780
        "y": -70
      tempMetlId: 11
    SQL (gold_current):
      position:
        x: -10
        "y": 160
      tempMetlId: 12
