type: "transformation"
version: "1.0"
pipeline:
  components:
    Extract Nested Data:
      type: "extract-nested-data-sf"
      sources:
      - "LAND_USER_DEMO"
      parameters:
        componentName: "Extract Nested Data"
        includeInputColumns: "Yes"
        columns:
        - name: "per_page"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA_VALUE"
          aliasName: "per_page"
          isArray: "false"
          include: "true"
        - name: "photos"
          datatype: "VARIANT"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA_VALUE"
          aliasName: "photos"
          isArray: "true"
          include: "true"
          childElements:
          - name: "photos-element"
            datatype: "VARIANT"
            size: "0"
            decimalPlaces: "0"
            columnName: "DATA_VALUE"
            aliasName: "photos-element"
            isArray: "false"
            include: "true"
            childElements:
            - name: "url"
              datatype: "VARCHAR"
              size: "0"
              decimalPlaces: "0"
              columnName: "DATA_VALUE"
              aliasName: "url"
              isArray: "false"
              include: "true"
            - name: "id"
              datatype: "NUMBER"
              size: "0"
              decimalPlaces: "0"
              columnName: "DATA_VALUE"
              aliasName: "id"
              isArray: "false"
              include: "true"
            - name: "src"
              datatype: "VARIANT"
              size: "0"
              decimalPlaces: "0"
              columnName: "DATA_VALUE"
              aliasName: "src"
              isArray: "false"
              include: "true"
              childElements:
              - name: "tiny"
                datatype: "VARCHAR"
                size: "0"
                decimalPlaces: "0"
                columnName: "DATA_VALUE"
                aliasName: "tiny"
                isArray: "false"
                include: "true"
              - name: "landscape"
                datatype: "VARCHAR"
                size: "0"
                decimalPlaces: "0"
                columnName: "DATA_VALUE"
                aliasName: "landscape"
                isArray: "false"
                include: "true"
              - name: "large2x"
                datatype: "VARCHAR"
                size: "0"
                decimalPlaces: "0"
                columnName: "DATA_VALUE"
                aliasName: "large2x"
                isArray: "false"
                include: "true"
              - name: "portrait"
                datatype: "VARCHAR"
                size: "0"
                decimalPlaces: "0"
                columnName: "DATA_VALUE"
                aliasName: "portrait"
                isArray: "false"
                include: "true"
              - name: "small"
                datatype: "VARCHAR"
                size: "0"
                decimalPlaces: "0"
                columnName: "DATA_VALUE"
                aliasName: "small"
                isArray: "false"
                include: "true"
              - name: "large"
                datatype: "VARCHAR"
                size: "0"
                decimalPlaces: "0"
                columnName: "DATA_VALUE"
                aliasName: "large"
                isArray: "false"
                include: "true"
              - name: "medium"
                datatype: "VARCHAR"
                size: "0"
                decimalPlaces: "0"
                columnName: "DATA_VALUE"
                aliasName: "medium"
                isArray: "false"
                include: "true"
              - name: "original"
                datatype: "VARCHAR"
                size: "0"
                decimalPlaces: "0"
                columnName: "DATA_VALUE"
                aliasName: "original"
                isArray: "false"
                include: "true"
            - name: "liked"
              datatype: "BOOLEAN"
              size: "0"
              decimalPlaces: "0"
              columnName: "DATA_VALUE"
              aliasName: "liked"
              isArray: "false"
              include: "true"
            - name: "height"
              datatype: "NUMBER"
              size: "0"
              decimalPlaces: "0"
              columnName: "DATA_VALUE"
              aliasName: "height"
              isArray: "false"
              include: "true"
            - name: "photographer"
              datatype: "VARCHAR"
              size: "0"
              decimalPlaces: "0"
              columnName: "DATA_VALUE"
              aliasName: "photographer"
              isArray: "false"
              include: "true"
            - name: "alt"
              datatype: "VARCHAR"
              size: "0"
              decimalPlaces: "0"
              columnName: "DATA_VALUE"
              aliasName: "alt"
              isArray: "false"
              include: "true"
            - name: "width"
              datatype: "NUMBER"
              size: "0"
              decimalPlaces: "0"
              columnName: "DATA_VALUE"
              aliasName: "width"
              isArray: "false"
              include: "true"
            - name: "photographer_url"
              datatype: "VARCHAR"
              size: "0"
              decimalPlaces: "0"
              columnName: "DATA_VALUE"
              aliasName: "photographer_url"
              isArray: "false"
              include: "true"
            - name: "avg_color"
              datatype: "VARCHAR"
              size: "0"
              decimalPlaces: "0"
              columnName: "DATA_VALUE"
              aliasName: "avg_color"
              isArray: "false"
              include: "true"
            - name: "photographer_id"
              datatype: "NUMBER"
              size: "0"
              decimalPlaces: "0"
              columnName: "DATA_VALUE"
              aliasName: "photographer_id"
              isArray: "false"
              include: "true"
        - name: "total_results"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA_VALUE"
          aliasName: "total_results"
          isArray: "false"
          include: "true"
        - name: "next_page"
          datatype: "VARCHAR"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA_VALUE"
          aliasName: "next_page"
          isArray: "false"
          include: "true"
        - name: "page"
          datatype: "NUMBER"
          size: "0"
          decimalPlaces: "0"
          columnName: "DATA_VALUE"
          aliasName: "page"
          isArray: "false"
          include: "true"
        outerJoin: "No"
        inputAlias: "i"
        arrayPrefix: "f"
        castingMethod: "Fail on invalid data"
        caseColumnAliasNames: "No"
    Calculator:
      type: "calculator"
      sources:
      - "Extract Nested Data"
      parameters:
        componentName: "Calculator"
        includeInputColumns: "Yes"
        calculations:
        - - "CURRENT_TIMESTAMP()"
          - "LOAD_TIME_V"
    Rewrite Table:
      type: "rewrite-table"
      sources:
      - "Calculator"
      parameters:
        componentName: "Rewrite Table"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "STG_USER_DATA"
        orderBy:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    LAND_USER_DEMO:
      type: "table-input"
      parameters:
        componentName: "LAND_USER_DEMO"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "LAND_USER_DEMO"
        columnNames:
        - "DATA_VALUE"
        timeOffset:
design:
  components:
    Extract Nested Data:
      position:
        x: -270
        "y": -30
      tempMetlId: 2
    Calculator:
      position:
        x: -130
        "y": -30
      tempMetlId: 3
    Rewrite Table:
      position:
        x: -30
        "y": -30
      tempMetlId: 4
    LAND_USER_DEMO:
      position:
        x: -420
        "y": -30
      tempMetlId: 1
