type: "transformation"
version: "1.0"
pipeline:
  components:
    Table Input:
      type: "table-input"
      parameters:
        componentName: "Table Input"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "land_orders"
        columnNames:
        - "o_id"
        - "o_amount"
        - "o_orderdate"
        timeOffset:
    Aggregate:
      type: "aggregate"
      sources:
      - "Table Input"
      parameters:
        componentName: "Aggregate"
        groupings:
        aggregations:
        - - "o_orderdate"
          - "Max"
        groupingType: "Group By"
    Table Output:
      type: "table-output"
      sources:
      - "Aggregate"
      parameters:
        componentName: "Table Output"
        warehouse: "[Environment Default]"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        targetTable: "temp_max_date"
        fixDataTypeMismatches: "No"
        columnMapping:
        - - "max_o_orderdate"
          - "max_date"
        orderBy:
        outputMode: "Append"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    Table Input:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    Aggregate:
      position:
        x: 170
        "y": 0
      tempMetlId: 4
    Table Output:
      position:
        x: 320
        "y": 0
      tempMetlId: 5
