type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      transitions:
        unconditional:
        - "Data Source (Google Sheets)"
      parameters:
        componentName: "Start"
    Incremental Load:
      type: "run-transformation"
      parameters:
        componentName: "Incremental Load"
        transformationJob: "Assignment_2/incremental_logic.tran.yaml"
        setScalarVariables:
        setGridVariables:
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
    Data Source (Google Sheets):
      type: "modular-google-sheets-input-v0"
      transitions:
        success:
        - "Incremental Load"
      parameters:
        componentName: "Data Source (Google Sheets)"
        componentId: "modular-google-sheets-input-v0"
        inputId: "google-sheets-input-v0"
        google-sheets-input-v0:
          connection:
            authType: "OAUTH_USER_TOKENS"
            secretReferenceId: "dpc-auth-google"
          connectionOptions:
          spreadsheetName: "orders_incremental - 1d5vbkKo21TLMn_AniyUeudrDD3J9MdXNj1-J0ayyGeA"
          containsHeaderRow: "Yes"
          mode: "BASIC"
          cellRange:
          dataSource: "orders_incremental_Sheet1"
          dataSelection:
          - "o_id"
          - "o_category"
          - "o_orderdate"
          dataSourceFilter:
          combineFilters: "AND"
          limit:
          autoDebug: "No"
        outputId: "snowflake-output-connector-v0"
        snowflake-output-connector-v0:
          warehouse: "[Environment Default]"
          database: "Incremental_Load"
          schema: "bronze"
          tableName: "orders_raw_stg"
          createTableMode: "APPEND"
          primaryKeys:
          cleanStagedFiles: "Yes"
          stagePlatform: "SNOWFLAKE"
          trimStringColumns: "No"
          stringNullIsNull: "No"
          snowflake#internalStageType: "USER"
      postProcessing:
        updateOutputMessage:
        updateScalarVariables:
design:
  components:
    Start:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    Incremental Load:
      position:
        x: 270
        "y": 0
      tempMetlId: 3
    Data Source (Google Sheets):
      position:
        x: 120
        "y": 0
      tempMetlId: 4
